[tox]
requires =
    tox>=4.0
env_list =
    py38
    py311
    py314
skip_missing_interpreters = true

[testenv]
description = Run pytest under {basepython}
platform = linux
package = wheel
wheel_build_env = .pkg
pass_env =
    GRAPH_TEST_*
deps =
    pytest>=8
    pytest-cov>=5
    fakeredis>=2.33.0
commands =
    pytest {posargs}
